### ISSUE TITLE
Thanks! Want a webpack build PR?

### ISSUE THREAD

**Issue by kfarr** [ctrlw/osm4vr#1]
Thanks for putting this repo together! I saw the `KaiRo-at/vrmap` repo back in the day and had wished for a [componentized version of it](https://github.com/KaiRo-at/vrmap/issues/1)! I appreciate your efforts to wrap this up in a simpler component.

To test this out in another project I did some work to make a build process and some other basic linting features:
https://github.com/ctrlw/osm4vr/compare/main...3DStreet:osm4vr:main

If you're interested I can do a PR

**Comment by ctrlw** [comment]
Thanks, glad to make your wish come true after 5 years :-)

The linter is a great idea, I'll try to incorporate it into my workflow. Any recommendation regarding the setup?

Regarding the webpack build process, I'm a bit hesitant to add this now as I don't have a need for it myself and am not yet sure about the direction of this project. I'll probably do some fixes and may come back to you regarding a PR at a later point.

If you have other inputs or requests, feel free to share, maybe they align with my own short-term plans.

**Comment by kfarr** [comment]
You're welcome to take a look and copy the linting config here, it's similar to other a-frame components:
https://github.com/3DStreet/osm4vr/blob/main/package.json#L10-L11 are the commands and the dependency is:
https://github.com/3DStreet/osm4vr/blob/main/package.json#L23

I'll close this ticket for now since webpack is not a priority at the moment.
