### ISSUE TITLE
Public attribution?

### ISSUE THREAD

**Issue by kfarr** [ctrlw/osm4vr#2]
Hi @ctrlw I wanted to share this work with a wider audience as we continue to integrate this with our open-source app https://github.com/3dstreet/3dstreet/

Would you like us to attribute "ctrlw" or is there another name / organization that you'd like us to mention and promote publicly as thanks for this work?

**Comment by ctrlw** [comment]
Hi Kieran, thanks for asking! ctrlw is fine for now

**Comment by kfarr** [comment]
Thanks! I'll close the ticket with an example of how we plan to attribute your work:
https://deploy-preview-54--3dstreet-docs-build-preview.netlify.app/blog/2024/10/25/announcing-open-street-map-and-3dstreet-integration#a-frame-component-for-osm-integration

Please let us know if there's anything else we can do to support your work.
